mitre/heimdall2

.github/workflows/e2e-backend-tests.yml, .github/workflows/e2e-ui-tests.yml, .github/workflows/frontend-tests.yml, .github/workflows/linter.yml, README.md, apps/frontend/vue.config.js, package-lock.json, package.json
Using npm install to install lerna was bad practice since it was overwriting the 'package-lock.json' at the root of the repository. Developers now will need to directly install lerna and then use lerna to bootstrap dependencies.
This also fixes a few small problems causing difficulty developing the application on Windows.
=> Require developers to install lerna globally

apps/frontend/src/components/cards/controltable/ControlTable.vue
This changes the the single-expand vs multi-expand switch to be reactive to the currently selected state.
=> Change single-expand and mutliple-expand to be reactive

apps/backend/src/database/database.service.spec.ts, apps/backend/src/database/database.service.ts, apps/backend/src/database/interfaces/delta-args.interface.ts, apps/backend/src/evaluation-tags/dto/create-evaluation-tag.dto.ts, apps/backend/src/evaluation-tags/dto/delete-evaluation-tag.dto.ts, apps/backend/src/evaluation-tags/dto/update-evaluation-tag.dto.ts, apps/backend/src/evaluation-tags/evaluation-tags.service.ts, apps/backend/src/evaluations/dto/update-evaluation.dto.ts, apps/backend/src/evaluations/evaluations.service.spec.ts, apps/backend/src/evaluations/evaluations.service.ts, apps/backend/test/constants/evaluation-tags-test.constant.ts, apps/backend/test/constants/evaluations-test.constant.ts, libs/interfaces/evaluation-tag/delete-evaluation-tag.interface.ts, libs/interfaces/evaluation/update-evaluation.interface.ts, libs/interfaces/index.ts
This PR adds functionality that lets evaluation tags be created, updated and deleted when updating an evaluation.
There is no associated issue for this, but it adds some expected behavior.
=> Evaluation Tags (CUD) via Evaluation API

apps/frontend/src/views/Compare.vue, apps/frontend/src/views/Results.vue
=> Fix styling on search bar when clicking on it in lite/dark mode

apps/backend/src/config/config.service.spec.ts, apps/backend/src/config/config.service.ts, apps/backend/test/constants/env-test.constant.ts, apps/frontend/vue.config.js
This adds a fallback method for configuring the environment, instead of only supporting a `.env` file, it will now fallback to reading any variables that are sourced in the environment.
The order goes as follows:
.env in `apps/backend/.env`
`process.env`
undefined
=> Add the ability to read all configuration from environment is no .env file is provided in the backend.

README.md
This moves the Docker instructions of the `Developers` section of the README and adds the new demo links.
=> Update README with new demo servers, restructure headings to be more clear

apps/backend/src/app.controller.ts, apps/backend/src/config/config.service.ts, apps/backend/src/config/dto/startup-settings.dto.ts, apps/frontend/src/components/global/UploadNexus.vue, apps/frontend/src/store/server.ts, apps/frontend/src/views/Login.vue, apps/frontend/src/views/Signup.vue, libs/interfaces/config/startup-settings.interface.ts, libs/interfaces/index.ts
=> Add support for a warning banner using the backend WARNING_BANNER env variable

.github/workflows/auto-approve.yml
This allows most PRs to require 1 review before merging, and will still require the tests to pass before the PR is automatically merged.
=> Auto approve Dependabot PRs

.github/workflows/backend-tests.yml, .github/workflows/e2e-ui-tests.yml, .github/workflows/frontend-tests.yml, .github/workflows/gh-pages.yml, .github/workflows/linter.yml, Dockerfile, Dockerfile.lite, apps/frontend/package.json, yarn.lock
Docker is building on node 14.x however the test suite is running on 12.x. Failures are happening on Docker and not on the test suite, this makes the versions consistent in order to attempt to avoid such errors.
Also  run vue upgrade and move appropriate deps from devDependencies. This is a suggested step as part of the vue-cli-service upgrade, https://cli.vuejs.org/migrating-from-v3/
=> Upgrade node to 14.x in GH Actions

apps/frontend/src/components/cards/ProfileData.vue, apps/frontend/src/views/Results.vue
A recent commit broke the Results view causing it to display both results and profiles. This reverts that change.
This also deduplicates the search input element so that the same one is displayed whether the application is in mobile view or full size view.
Also fixes a warning from ProfileData that was being displayed on the Developer Console.
=> Fix results and profile view to only display their respective files

apps/frontend/src/components/cards/treemap/Cell.vue
Without this declaration, strange behavior was happening only on production builds. Adding it back has corrected the missing Treemap. Fixes #370
=> Replace removed Component name for Cell.vue

.github/workflows/gh-pages.yml
Going to Settings on Github and setting a CNAME simply commits the CNAME to the gh-pages branch. Without explicitly setting the CNAME in the branch on every deploy it will be deleted on every release.
=> Set CNAME on deploy

apps/frontend/src/components/cards/controltable/ControlTable.vue
Closes #406, sets ControlTable to use single-expand by default.
=> Switch to single-expand default

apps/backend/src/users/users.service.spec.ts, apps/backend/test/users.e2e-spec.ts
The return codes for a user changing their profile information were changed to avoid our global 401 catch all to handle bad tokens.
=> Fix broken tests caused by change in return codes

apps/frontend/src/components/cards/controltable/ControlRowCol.vue, apps/frontend/tests/unit/ControlRowCol.spec.ts
small fix introduced in 2.3.3 with the failed test results message vs the code_desc
Fixes #494
Signed-off-by: Aaron Lippold <lippold@gmail.com>
=> Small fix to display the correct sub-part of the failure message in the test results

.github/workflows/auto-approve.yml, .github/workflows/backend-tests.yml, .github/workflows/e2e-ui-tests.yml, .github/workflows/frontend-tests.yml, .github/workflows/linter.yml
We're using `ubuntu-latest` as GitHub CI executor. This will change soon
from Ubuntu 18.04 to 20.04.
This commit checks if we can keep `ubuntu-latest` or if we should use
`ubuntu-18.04`.
=> Bump ubuntu where CI executed on to 20.04

apps/backend/src/main.ts
This setting causes the application to not load for users when accessing remotely over HTTP: https://github.com/mitre/heimdall2/issues/787
This is intended as a stop-gap until #791 is addressed.
=> Remove upgrade-insecure-requests setting from Helmet

.vscode/launch.json, README.md
Using the vscode launch.json no longer works due issues with the types folder. Removing it and adding alternative instructions in the README
=> Remove nest debugging from the vscode launch.json

README.md
Closes #850. Adds links to the new [Environment Variables Configuration](https://github.com/mitre/heimdall2/wiki/Environment-Variables-Configuration) page in the wiki. This PR is also meant for comments on the wiki page as I don't believe there is a way to comment on it directly.
=> Add links to Environment Variables Configuration in Wiki

apps/frontend/public/index.html
Currently, Heimdall is loading as a blank page in IE. This provides users with a more explicit message instructing them to use a different browser.
=> Show users of IE that we do not support their current browser

apps/frontend/src/store/app_info.ts
This way, users aren't shown an error when rate-limited by the GitHub API
=> Skip the default axios interceptors for Github API Requests

apps/frontend/src/components/cards/StatusCardRow.vue, apps/frontend/src/store/status_counts.ts, apps/frontend/tests/unit/parsing_and_counting.spec.ts
This clarifies the status counts along the top of Heimdall, removes the total count, and makes the count of passing and failing individual controls more clear in the failed box. It also stops the counting of "FailedOutOf", "NotApplicableTests", "NotReviewedTests", "ErroredOutOf", "ErroredTests", and "TotalTests" since those counts are no longer used anywhere and counting them would be a waste of CPU cycles.
Closes #80
=> Cleanup Status Counts

Dockerfile, Dockerfile.lite, package.json
This fixes an apparent segfault in node-bcrypt and also makes it possible to build in offline environments.
Instead of using the lerna located in the repo, `npx lerna` was reaching out to the internet. This was causing another failure when building offline.
=> Build node-bcrypt dependencies in Docker instead of reaching out to GitHub

.github/mergify.yml
The original one included unnecessary checks since mergify respects the branch protection rules.
=> Cleanup mergify configuration

test/support/components/UploadModal.ts
This potentially fixes an issue with the E2E UI tests where they keep failing over and over due to the database filename element potentially being masked by another element.
=> Fix consistent E2E UI test failure by forcing a click

Dockerfile, Dockerfile.lite, apps/backend/package.json
Make Dockerfile more generic to allow for building against different base containers.
Move `oauth2-mock-server` to `devDependencies` since it is not required for building (and has very stringent node requirements).
=> More Dockerfile cleanup

apps/frontend/.eslintrc.js, apps/frontend/tests/unit/Compare.spec.ts
Makes ESLint warn about unused imports and variables on the frontend.
=> Enable @typescript-eslint/no-unused-vars for Frontend

apps/backend/src/evaluations/evaluations.controller.spec.ts, apps/backend/src/evaluations/evaluations.controller.ts, apps/backend/src/evaluations/evaluations.module.ts
Previously Heimdall was always showing a relative URL
=> Leverage EXTERNAL_URL to show an absolute URL to users uploading results via the API

README.md
This was a holdover from Heimdall Lite 1.0 which is not currently relevant.
=> Remove PDF Report and Print View from feature list

apps/backend/src/interceptors/create-evaluation-interceptor.ts
Closes #1191, checks if evaluationTags is an empty string before splitting.
=> Prevent Creating Empty Tag on Upload

apps/frontend/package.json, apps/frontend/src/components/cards/controltable/ControlRowDetails.vue, apps/frontend/vue.config.js, yarn.lock
Heimdall was pulling in 2 prism components but not using both of them. This removes the unused one and cleans up the imports of the one we do use.
=> Remove unnecessary imports of Prism

apps/frontend/vue.config.js
This fixes an issue where builds can fail just do to linter errors.
=> Make linter errors warnings instead of errors on build.

.github/workflows/backend-tests.yml, .github/workflows/frontend-tests.yml, .github/workflows/gh-pages.yml, .github/workflows/linter.yml, package.json, test/package.json
This should speed things up due to not having to download the large cypress package for unrelated tests.
=> Speed up CI runs by only installing nessecary packages

.github/mergify.yml
The updated version of dependabot does not support automatic PR merging. This sets up mergify to do it instead.
=> Automatically merge dependabot updates.

apps/frontend/src/components/cards/controltable/ControlRowDetails.vue
Closes #1305, adds all `c.hdf.descriptions` to the details tab.
=> Show all subdescriptions on the Descriptions page

apps/frontend/src/components/global/ExportCaat.vue
This re-adds support for respecting filters in ExportCAAT after #1190.
=> Respect Filter in CAAT Export

.gitignore, Dockerfile, apps/backend/package.json, apps/backend/src/app.module.ts, apps/backend/tsconfig.json, test/package.json
All of the backend dependencies are required to execute the server image. By not hoisting them it is possible to isolate the packages required and only install those on the server image, limiting the number of dependencies installed and slimming ~300MB from the production image.
=> Do not hoist backend dependencies in order to slim server image

apps/backend/.env-example
Fixes .env-example missing documentation for usage of GitHub enterprise instances as an authentication method via alternative authentication.
Changes were also made to the wiki to add this documentation and documentation for Open ID Connect.
=> Add Missing Variables to .env-example

apps/frontend/src/components/global/upload_tabs/DatabaseReader.vue, apps/frontend/src/components/global/upload_tabs/EditEvaluationModal.vue, apps/frontend/src/components/global/upload_tabs/GroupFileList.vue, apps/frontend/src/components/global/upload_tabs/LoadFileList.vue, apps/frontend/src/views/Results.vue
Closes #906, sorts evaluations in DatabaseReader table by their groups. Evaluations that belong to multiple groups are duplicated in the table.
=> Show Evaluations by Groups

.gitignore, docker-compose.yml
Avoid users mistakenly committing their SSL certificates to git, avoid naming conflicts by allowing docker compose to pick the name of the container.
=> Gitignore NGINX Certificates, do not specify nginx container name

apps/frontend/src/components/global/RegistrationModal.vue
This prevents dismissing the registration modal by accident, and then have to reload the page to get it back.
=> Prevent Signup Modal From Being Dismissed

apps/frontend/package.json, yarn.lock
The dart sass developers have decided that hiding deprecation warnings, even if they are out of our control, should not be allowed: https://github.com/sass/libsass/issues/2822#issuecomment-482914373
They have recommended locking to a version that does not have the warnings so this PR does just that.
=> Lock to old version of Dart sass

apps/frontend/src/components/global/UploadNexus.vue
Closes #115. Forces v-group-slider to recalculate its position on switching tabs.
=> Force v-group-slider to recalculate position on switching tabs

apps/frontend/src/components/cards/controltable/ControlTable.vue
Closes #226. Only pins control table headers on [medium displays and larger](https://vuetifyjs.com/en/features/breakpoints/).
=> Fix Control Table Vertical Space Problems on Small Displays

.github/mergify.yml, .github/workflows/auto-approve-and-merge.yml
Stop using mergify for merging Depndabot PRs, use Github Action instead
=> Update Mergify and Dependabot merge configurations

apps/backend/src/authn/ldap.strategy.ts
This fixes the server failing to create an account when multiple email values are present on the LDAP account.
=> Use First LDAP Email Available if Multiple

apps/backend/.env-example, apps/backend/src/authn/gitlab.strategy.ts
Closes #1553, adds `GITLAB_BASEURL` environment variable to specify a custom Gitlab instance.
=> Add Support for Custom Gitlab Base URL

apps/frontend/src/views/Compare.vue
Closes #1535, ensures evaluations have a matching IEvaluation before loading its TagRow on compare view.
=> Ensure Evaluation is from Database Before Loading TagRow on Compare View

apps/frontend/src/components/global/groups/GroupManagement.vue, apps/frontend/src/components/global/groups/GroupUsers.vue
Closes #1651. Can't click on group members chip more than once.
=> Fixed bug where you couldn't open group members dialog more than once

apps/backend/src/main.ts
Current cookie expiration is 82 years, this is very long for how long the oauth workflow should reasonably take.
The JWT secret is really only intended for JWT, since these are not for long standing sessions, a short term session is acceptable.
=> Set default cookie expiration to much lower, do not use JWT for secrets

apps/frontend/src/components/global/UserModal.vue
Closes #1640. Allow role changes for identity provider login created users.
=> Fixed issue where you couldn't update role of LDAP user

apps/backend/src/authn/authn.service.ts
Closes #1775, limits admin JWT tokens to 10 minutes.
=> Limit Admin JWT Token Validity to 10 Minutes

apps/frontend/src/store/data_filters.ts
=> Rename raw_nist_tags to rawNistTags for nist search

docker-compose.yml
Closes #2063, removes exposed port 3000 from docker-compose.yml.
=> Remove Access to Port 3000 from docker-compose.yml

libs/hdf-converters/src/asff-mapper.ts
Closes #2259, trims extra newlines from Prowler ASFFs to ensure data is converted correctly.
=> Trim ASFF Input before processing

apps/frontend/src/components/global/Topbar.vue, apps/frontend/src/views/Admin.vue, apps/frontend/src/views/Base.vue, apps/frontend/src/views/Groups.vue
Adds an obvious way to go back to the previous page on the groups and admin page.
=> Add back button to Groups and Admin pages

apps/frontend/public/static/export/cklExport.ckl
Closes #2813. Adds a field now required by STIG Viewer
=> Specify classification type on CKL Export

apps/frontend/src/components/global/ExportSplunkModal.vue, apps/frontend/vue.config.js, libs/hdf-converters/src/converters-from-hdf/splunk/reverse-splunk-mapper.ts, libs/hdf-converters/src/splunk-mapper.ts, libs/hdf-converters/src/utils/global.ts, tsconfig.json
This fixes an issue where objects of a certain type were not being created properly
See [this](https://stackoverflow.com/questions/51860043/javascript-es6-typeerror-class-constructor-client-cannot-be-invoked-without-ne) link for information on a similar bug someone was having.
* Use `@babel/preset-env` in Vue Config
* Change Winston usage to import the functions/objects directly instead of using the default import
=> Fix issue where certain filetypes wouldn't be uploaded via fingerprinting

libs/hdf-converters/src/asff-mapper/asff-mapper.ts
1) Split on FindingProviderFields.Types where there might have been
fewer than 3 slashes.
2) Fix for filenames (on at least windows) by swapping the bar with a
hyphen.
3) Fix the refs.urls where the transform wasn't working properly.
=> Three fixes

libs/hdf-converters/src/sonarqube-mapper.ts, test/support/server/SonarQube.json
Issue
===
Sonarqube2hdf failing with bad request caused by pulling closed vulnerabilities. The source pulls **all** the vulnerabilities, then for each vulnerability pulls the source code associated with it.  Vulnerabilities which are closed  causes an error because the file it was in no longer exists. This is the cause of the  BAD REQUEST is requesting source that no longer exists.
Solution
======
Only pull open and reopened vulnerabilities, this will ensure that the files which the vulnerabilities exists will still exist.
=> only pull open vulnerabilities for sonarqube2hdf as closed vulnerabilities

.gitignore, README.md, apps/backend/src/apikeys/apikey.controller.ts, setup-docker-env.sh
These changes stemmed from needing to document how to create an API Key programmatically. In doing so, we found some updates to documentation and ease of use necessary.
For reference, the new wiki to instruct how to create the API Key programmatically is [here](https://github.com/mitre/heimdall2/wiki/Programmatic-API-Key-Generation)
- Edited the error message for the setup-docker-env script if the .env file already exists
- Updated setup-docker-env script to accept "y" then enter for API Key generation
- Added in changes from Camden's branch to allow the user to be referenced by email instead of just userId
=> Updates for programmatic API creation use case

apps/backend/config/app_config.ts
This should also include commits 88ada221e6344094db9e838f7d72ed6786be376e and c9c36defd49158375c52a34d120072f1ed4f3163 but I was being bad and pushing to master for those.
The Heroku deployment was changed to use DATABASE_SSL_INSECURE (i.e. the default behavior before the ssl pr) since there shouldn't be prod data in it anyways.
=> Fixes required to make it work on heroku

libs/hdf-converters/src/veracode-mapper.ts
Our team found a bug that when a veracode xml file is imput without a sca section, the fie file errors out due to the .map happening on a nonexistant field, this code remedies that
=> made a change that fixes a bug for when sca tags are absent

apps/backend/package.json, yarn.lock
it seems like puppeteer was originally used for doing the ui testing for heimdall server, but that code was transitioned out to a top level directory (/tests as opposed to /apps or /libs) when the ui was deduped between server and lite, and then was also converted to being cypress
=> removed puppeteer dependencies since it was no longer being used

apps/backend/config/app_config.ts, apps/backend/seeders/20200514154327-create-administrator.js
resolves #4064 
Fundamental problem was that the sequelize cli commands (and code) is only run on db migration, which isn't actually a part of our tests as far as I'm aware and is how this problem wasn't noted since I know I at least don't do a db migration frequently esp if there wasn't a backend change.  To make sure a similar problem doesn't occur again, we should modify/add a workflow action to test this.
Signed-off-by: HenryXiaoHX <hxiao@ucsd.edu>
=> Fix sequelize cli typescript compilation issue

apps/frontend/src/types/v-clipboard/index.d.ts, apps/frontend/tsconfig.json, yarn.lock
added types override to deal with the fact that the types only work with vue3 even though the library works fine with vue2
should have also included https://github.com/mitre/heimdall2/commit/e6440200cdfa127e73245a7b7706820ac213f7f3 but I screwed up and pushed that straight to master
=> swap clipboard library

apps/frontend/src/components/generic/InputDialog.vue
resolves #4465 
v-card-titles have their css for word-break set to break-all (i.e. on any character).  changed it to break-word so that it doesn't look as awkward
=> fix wordwrap for api key modal

apps/frontend/public/index.html
- Removes jQuery import used in non-HTML Export files
- Extension of Export HTML refactor
=> Remove jQuery import

apps/frontend/src/components/cards/StatusChart.vue
Resolves: https://github.com/mitre/heimdall2/issues/4817
copy pasted the code from the compliance chart module.  this is a workaround until the html export is merged in which will then allow us to replace this code with a utility function
=> Truncate compliance percentage in the comparison view

apps/frontend/src/components/cards/EvaluationInfo.vue
=> Undefined Evaluation Bug Fix

apps/frontend/src/components/cards/controltable/ControlRowDetails.vue
Resolves #5418 
Still showing up in actual profile error situations
Sample file from original issue: https://github.com/mitre/heimdall2/issues/5226
No longer showing up in overlays
Sample file from new issue: https://github.com/mitre/heimdall2/issues/5418
=> Fix error message incorrectly showing up for overlay profile results

.github/workflows/release-server-to-docker.yml
Ironbank deployment pipeline gives an error during the lint-and-image-inspect job:
```
$ python3 "${PIPELINE_REPO_DIR}/stages/validate-container-repository/lint/validate_hardening_manifest.py"
| hardening_manifest           | INFO     | Validating schema
| hardening_manifest           | INFO     | This task will exit if not completed within 2 minutes
| hardening_manifest           | ERROR    | Hardening Manifest failed jsonschema validation
| hardening_manifest           | ERROR    | Verify Hardening Manifest content
| hardening_manifest           | ERROR    | {'tag': 'mitre/heimdall2:2.10.4', 'url': 'docker://docker.io/mitre/heimdall2@'} is not valid under any of the given schemas
```
which indicates that the url is missing the SHA commit hash at the end. Code has been adjusted to …
=> Fix Ironbank Deployment Pipeline Error

Dockerfile, apps/backend/src/authn/oidc.strategy.ts, apps/backend/src/authn/okta.strategy.ts, apps/frontend/src/views/Login.vue
Closes: #5719 
To test:
1. Setup Okta development server
2. Integrated local heimdall build with Okta dev server via App integrations
3. Stored the client id, client secret, external url, and okta domain as env variables for heimdall
4. Built Heimdall using the docker build to allow for https (http does not work with the okta integration)
5. Created users in okta and assigned them to Heimdall, had to assign them a username for it to work correctly)
6. Also had to disable GP to test the integration successfully
Added documentation here for testing Okta integration - https://github.com/mitre/heimdall2/wiki/Heimdall-Authentication-Methods#testing
=> Update okta.strategy.ts to work with passport-openidconnect 0.1.1

README.md, package.json, setup-docker-env.bat
This modifies the package.json file to use the .env file located in ./apps/backend/ rather than the root directory. 
This also modifies the readme to be more explicit about which .env is being used and where it's located for both dockerized and locally hosted application builds.
Documentation was previously unclear and stated that the .env file in ./apps/backend/ is what is used for local builds even though it was actually pulling from the .env in the root directory?
=> Package.json Fix

apps/frontend/src/components/global/ExportCKLModal.vue, apps/frontend/src/components/global/ExportJson.vue
Provide a checkbox that normalizes (proper formats) the profile title (name). Also fixes issue # #2375
Example, if the name is: `redhat-enterprise-linux-8-stig-baseline`
It normalizes to:  'Redhat Enterprise Linux 8 Security Technical Implementation Guide`
Process exchanges profile titles that end with 'stig-baseline', 'cis-baseline', 'srg-baseline' to Security Technical Implementation Guide and capitalizes all preceding words removing the dashes.
Without applying title formatting:
After applying title formatting:
=> Add option to normalize export ckl profile name

libs/hdf-converters/sample_jsons/gosec_mapper/gosec-hdf-withraw.json, libs/hdf-converters/src/gosec-mapper.ts, libs/hdf-converters/test/mappers/forward/gosec_mapper.spec.ts
- Fix `impact` to refer to GoSec's `severity` field.
- Other minor adjustments to mapper.
=> GoSec Mapper `impact` Fix

libs/hdf-converters/src/ckl-mapper/checklist-metadata-utils.ts
When checklist metadata is invalid, the resulting error message was rather difficult to interpret due to its structure. 
Previously: 
```
Invalid checklist metadata fields: Host FQDN (badfqdn.2), Host MAC (aa-bb---invalid) Profile red hat 7: Invalid checklist profile metadata fields: Release date must be a valid date (2023/29/01)
```
It is now more readable now that it is spread out on multiple lines. Example:
```
Invalid checklist metadata fields:
Host FQDN (badfqdn.2)
Host MAC (aa-bb---invalid)
In profile red hat 7:
Release date must be a valid date (2023/29/01)
```
=> Format error message when validating checklist metadata

.github/workflows/push-lite-to-docker.yml, .github/workflows/push-server-to-docker.yml, .github/workflows/release-lite-to-docker.yml, .github/workflows/release-server-to-docker.yml, Dockerfile, Dockerfile.lite
=> Docker improvements

libs/hdf-converters/sample_jsons/attestations/triple_overlay_profile_sample.json, libs/hdf-converters/src/utils/attestations.ts, libs/hdf-converters/test/attestations/attestations.spec.ts
When applying an attestation to an overlay file, we were getting the following error:
`"TypeError: Cannot read properties of undefined (reading 'status')"`
because the overlay file had the same control listed in multiple profile objects of the HDF file. Not every control instance has results because of it being an overlay file. This will catch that issue and apply the attestation once the results exist.
=> Fix Apply Attestation: "TypeError: Cannot read properties of undefined (reading 'status')"

libs/hdf-converters/sample_jsons/checklist_mapper/multiple_mac_addresses_metadata.json, libs/hdf-converters/sample_jsons/checklist_mapper/sample_input_report/multiple_mac_addresses_metadata.ckl, libs/hdf-converters/src/ckl-mapper/checklist-metadata-utils.ts, libs/hdf-converters/test/mappers/forward/checklist_mapper.spec.ts, libs/hdf-converters/test/mappers/reverse/checklist_reverse_mapper.spec.ts
Resolves the input part of #6512 
- refactor checklist mappper test
- add test for file with multiple mac addresses
- update checklist_metadata_utils to be able to validate a hostmac address string with multiple mac addresses
- allows export with more than one mac address
=> Update Checklist Mapper Import to Allow Multiple Mac Addresses

libs/hdf-converters/package.json, yarn.lock
fix fast-xml-parser to 4.5.4 because the 5.X versions cause issues with using eval() and break the docker build
The docker build had this issue using fast-xml-parser 5.0.6
Content-Security-Policy :The page's settings blocked a JavaScript eval (script-src) from being executed because it violates the following directive: "script-src 'self'" (Missing 'unsafe-eval')
Reference: https://github.com/NaturalIntelligence/fast-xml-parser/blob/af4f1d2d4da800202ad68e63f25a07a0ad9c201c/lib/fxp.cjs
https://github.com/NaturalIntelligence/fast-xml-parser/issues/733
Note commentator saying this is now esm native, which also causes issues
=> Fix fast-xml-parser to avoid eval() use
