- .github/workflows/test.yml
Signed-off-by: Sam Sunvold <ssunvold@mitre.org>
> Updated workflow

- package.json
- src/authz/policy.model.ts
- src/pipes/passwords-match.pipe.spec.ts
- src/users/users.service.spec.ts
- test/test.constants.ts
> Added unit tests for passwords-match.pipe

- src/pipes/password-complexity.pipe.spec.ts
- src/pipes/password-complexity.pipe.ts
- src/users/users.service.spec.ts
Have questions for Kyle, so this isn't 100% done. However, it's pretty close to being finished
> Password complexity pipe unit tests

- package.json
- src/pipes/password-change.pipe.spec.ts
- src/pipes/password-change.pipe.ts
- src/pipes/password-complexity.pipe.spec.ts
- src/pipes/password-complexity.pipe.ts
- src/pipes/passwords-match.pipe.spec.ts
- src/pipes/passwords-match.pipe.ts
- test/test.constants.ts
Will need to rebase with master after PR#16 is closed.
> More password validation unit tests

- src/authz/authz.service.spec.ts
- src/authz/authz.service.ts
- src/config/config.service.spec.ts
- test/constants/env-test.constant.ts
- test/constants/policy-test.constant.ts
- test/constants/users-test.constant.ts
> Added authz service unit tests and logging

- src/evaluations/dto/create-evaluation.dto.ts
- src/evaluations/dto/evaluation.dto.ts
- src/evaluations/dto/update-evaluation.dto.ts
- src/evaluations/evaluations.controller.ts
- src/evaluations/evaluations.module.ts
- src/evaluations/evaluations.service.ts
Still a lot of work to do inside the controller file, also not sure if something needs to be modified in the service.ts file. Atom was yelling about missing the EvaluationsService that I'm trying to import at the beginning.
> Evaluation controller

- migrations/20200720195534-add_data_to_evaluations.js
- src/evaluations/dto/create-evaluation.dto.ts
- src/evaluations/dto/evaluation.dto.ts
- src/evaluations/dto/update-evaluation.dto.ts
- src/evaluations/evaluation.model.ts
- src/evaluations/evaluations.service.ts
This puts an arbitrary data field on Evaluation model so that results can be included and viewed.
> Evaluations Upload API

- package-lock.json
- package.json
- src/app.controller.ts
- src/app.module.ts
- tsconfig.build.json
- tsconfig.json
This will eventually include the full heimdall-lite source code in the `client` directory as part of this one.
> WIP: Allow for serving heimdall-client as a static asset

- src/evaluation-tags/dto/evaluation-tag.dto.ts
- src/evaluations/dto/evaluation.dto.ts
- src/evaluations/evaluations.controller.spec.ts
- src/evaluations/evaluations.service.spec.ts
- src/evaluations/evaluations.service.ts
- src/users/users.controller.spec.ts
- src/users/users.service.spec.ts
- test/constants/evaluations-test.constant.ts
- test/evaluations.e2e-spec.ts
> Evaluation tests

- apps/backend/src/evaluation-tags/dto/delete-evaluation-tag.dto.ts
- apps/backend/src/evaluation-tags/dto/update-evaluation-tag.dto.ts
- apps/backend/src/evaluations/dto/create-evaluation.dto.ts
- apps/backend/src/evaluations/dto/update-evaluation.dto.ts
- apps/backend/src/users/dto/create-user.dto.ts
- apps/backend/src/users/dto/delete-user.dto.ts
- apps/backend/src/users/dto/update-user.dto.ts
- apps/backend/src/users/users.service.spec.ts
- apps/backend/test/constants/users-test.constant.ts
- apps/backend/test/integration/authentication.spec.ts
- apps/backend/test/integration/registration.spec.ts
- apps/backend/test/users.e2e-spec.ts
> Add extra class validation to DTOs on the backend

- apps/backend/jest-puppeteer.config.js
- apps/backend/src/authz/dto/policy.dto.ts
- apps/backend/src/database/database.service.ts
- apps/backend/src/evaluations/evaluations.service.ts
- apps/backend/test/users.e2e-spec.ts
> Fix sonar and lgtm issues backend

- apps/backend/package.json
- apps/backend/src/authn/authn.controller.ts
- apps/backend/src/authn/authn.service.ts
- apps/backend/src/authz/authz.service.ts
- apps/backend/src/authz/policy.model.ts
- apps/backend/src/database/database.service.spec.ts
- apps/backend/src/evaluation-tags/dto/create-evaluation-tag.dto.ts
- apps/backend/src/evaluation-tags/dto/delete-evaluation-tag.dto.ts
- apps/backend/src/evaluation-tags/dto/update-evaluation-tag.dto.ts
- apps/backend/test/evaluations.e2e-spec.ts
- apps/backend/test/users.e2e-spec.ts
- apps/backend/tsconfig.json
- apps/frontend/tsconfig.json
- package-lock.json
- tsconfig.json
> 128 backend no implicit any

- apps/frontend/package.json
- apps/frontend/src/components/global/UploadNexus.vue
- apps/frontend/src/components/global/upload_tabs/SampleList.vue
- apps/frontend/src/sass/main.scss
- package-lock.json
Updrading vuetify broke UploadNexus colors. Needed to specify background color  on v-list and v-tabs. 
Closes https://github.com/mitre/heimdall2/issues/63
> Upgrade vuetify

- apps/frontend/src/components/cards/controltable/ControlTable.vue
Make Results view data part of the Results Page. This will remove 3 srollbar.
> Update Results View Data

- apps/frontend/src/components/global/UploadNexus.vue
- apps/frontend/src/components/global/upload_tabs/SampleList.vue
- apps/frontend/src/sass/main.scss
- apps/frontend/src/views/Results.vue
Updated main.scss with v-list and v-tabs. Color on search bar and Title bar on Result Data fixed.
> fix colors for components in results page. 

- apps/frontend/.eslintrc.js
- apps/frontend/src/App.vue
- apps/frontend/src/components/cards/EvaluationInfo.vue
- apps/frontend/src/components/cards/ProfData.vue
- apps/frontend/src/components/cards/comparison/CompareRow.vue
- apps/frontend/src/components/cards/comparison/DeltaView.vue
- apps/frontend/src/components/cards/controltable/ControlRowCol.vue
- apps/frontend/src/components/cards/controltable/ControlRowDetails.vue
- apps/frontend/src/components/cards/controltable/ControlRowHeader.vue
- apps/frontend/src/components/cards/controltable/ControlTable.vue
- apps/frontend/src/components/generic/ApexLineChart.vue
- apps/frontend/src/components/global/AboutModal.vue
- apps/frontend/src/components/global/HelpAboutDropdown.vue
- apps/frontend/src/components/global/HelpModal.vue
- apps/frontend/src/components/global/Toolbar.vue
- apps/frontend/src/components/global/UploadNexus.vue
- apps/frontend/src/components/global/upload_tabs/splunk/FileList.vue
- apps/frontend/src/views/BaseView.vue
- apps/frontend/src/views/Compare.vue
- apps/frontend/src/views/Profile.vue
- apps/frontend/src/views/Results.vue
- apps/frontend/src/views/Usergroup.vue
Before:
`<SomeElement></SomeElement>`
After
`<SomeElement />`
> Update vue/html-self-closing eslint rule to generically favor self-closing tags

- apps/frontend/src/views/Results.vue
Closes #171. Removes inverted tag from top search bar
> Fix Search Bar Color

- apps/frontend/src/views/BaseView.vue
- apps/frontend/src/views/Login.vue
- apps/frontend/src/views/Results.vue
- apps/frontend/src/views/Signup.vue
Closes #170. Fixes depreciation issues
> Fix depreciation issues

- apps/backend/.eslintrc.js
- apps/backend/src/pipes/password-change.pipe.ts
- apps/backend/src/pipes/password-complexity.pipe.ts
- apps/backend/src/pipes/passwords-match.pipe.ts
- apps/frontend/.eslintrc.js
- apps/frontend/package.json
- apps/frontend/src/components/cards/StatusCardRow.vue
- apps/frontend/src/components/cards/comparison/CompareRow.vue
- apps/frontend/src/components/cards/treemap/Treemap.vue
- apps/frontend/src/components/generic/ApexPieChart.vue
- apps/frontend/src/components/global/ExportNist.vue
- apps/frontend/src/components/global/sidebaritems/SidebarFile.vue
- apps/frontend/src/components/global/upload_tabs/FileReader.vue
- apps/frontend/src/components/global/upload_tabs/aws/FileList.vue
- apps/frontend/src/components/global/upload_tabs/aws/S3Reader.vue
- apps/frontend/src/components/global/upload_tabs/splunk/AuthStep.vue
- apps/frontend/src/store/color_hack.ts
- apps/frontend/src/store/data_filters.ts
- apps/frontend/src/utilities/aws_util.ts
- apps/frontend/src/utilities/treemap_util.ts
- apps/frontend/src/views/Landing.vue
- apps/frontend/tests/unit/Results.spec.ts
- apps/frontend/tests/unit/parsing_and_counting.spec.ts
- apps/frontend/tests/util/testingUtils.ts
- yarn.lock
> Add more descriptive unused-imports/no-unused-imports

- apps/frontend/src/components/global/upload_tabs/FileReader.vue
> Add back fileReader load function

- Procfile
- app.json
This is an attempt to add automatic database migrations to Heroku and fix review applications by specifying a basic app.json for review apps.
> Add procfile & app.json for Heroku

- apps/frontend/src/views/Login.vue
- apps/frontend/src/views/Signup.vue
Closes #212, uses @keyup.enter to navigate the login/signup forms.
> Use keyup.enter to navigate login/signup form

- apps/frontend/src/components/cards/EvaluationInfo.vue
- apps/frontend/src/components/cards/comparison/ProfileRow.vue
- apps/frontend/src/store/server.ts
- apps/frontend/src/views/Compare.vue
> Add comment documenting why try/catch block is empty in server mode

- apps/frontend/src/components/global/HelpAboutDropdown.vue
Fixes the help/about dropdown displaying weird on smaller displays.
> Fix dropdown arrow on help/about dropdown

- apps/frontend/package.json
Fixes #407 
Updates the inspecjs schema to be more permissive of different waiver forms.
Signed-off-by: Jacob Henry <jchenry@mitre.org>
> Fix inspecjs version bump to 0.12.2

- apps/backend/src/users/users.service.ts
- apps/frontend/src/components/global/UserModal.vue
- apps/frontend/src/mixins/UserValidatorMixin.ts
- apps/frontend/src/views/Login.vue
Closes #475. Adds an Incorrect Password message if you input the wrong password.
> Add Incorrect Password Message to User Profile

- apps/backend/test/integration/registration.spec.ts
- apps/frontend/src/views/Signup.vue
Re-adds checks to registration after changing mixins to be functions instead of getters.
> Change Frontend Checks for Registration Fields

- apps/frontend/src/components/global/Sidebar.vue
- apps/frontend/src/components/global/sidebaritems/DropdownContent.vue
- apps/frontend/src/enums/Trinary.ts
- apps/frontend/src/store/data_filters.ts
1) Removed 'Files' subheader and surrounding v-list on the expander.
2) Made 'Comparison View' into a toggle.
3) Made 'De/Select all' into a trinary checkbox.
4) Cleaned up DropdownContent.
> Updated DropdownContent

- apps/frontend/src/components/global/Sidebar.vue
> Increase sidebar width to 600px

- apps/frontend/src/components/global/Topbar.vue
- apps/frontend/src/views/BaseView.vue
- apps/frontend/src/views/Landing.vue
Closes #563, adds the top bar to the landing page.
> Display Topbar on Landing

- apps/frontend/src/components/cards/controltable/ControlRowCol.vue
- apps/frontend/src/components/cards/controltable/ControlRowHeader.vue
- apps/frontend/src/components/cards/treemap/Cell.vue
- apps/frontend/src/components/cards/treemap/Treemap.vue
- apps/frontend/src/components/global/ExportCaat.vue
Fixed all the frontend issues except for the text storage one which'll require significant refactoring to resolve.
Closes #149
> Fix LGTM scan issues

- apps/backend/.sequelizerc
- apps/backend/src/database/database.module.ts
This may fix the seemingly random connection failures we are receiving on Heroku.
> Add the ability to connect to Postgres with SSL

- apps/frontend/src/components/cards/controltable/ControlRowCol.vue
- apps/frontend/src/components/cards/controltable/ControlRowDetails.vue
The application was not properly wrapping text for "Test" field in ControlRowCol's. Fix the wrapping and respect newlines in Test and Result fields.
Fixes #761
> Fix formatting of ControlRowCol's

- apps/backend/src/main.ts
Was previously blocked in server mode by helmet.
> Allow S3 login from Heimdall Server

- apps/frontend/src/components/global/login/LocalLogin.vue
Accidentally removed signup button when moving to LocalLogin component.
> Re-add signup button

- apps/frontend/src/components/global/sidebaritems/SidebarFileList.vue
Closes #218. Prevents users from uploading an existing file into the database.
> Prevent User from Accidentally Re-Uploading Evaluations

- apps/frontend/src/components/global/upload_tabs/LoadFileList.vue
Previously search was only working on lowercase.
> Search on lowercase and uppercase filenames

- apps/frontend/src/views/Compare.vue
Closes #872. Removes the top padding from the results comparison title.
> Fix "Results Comparison" Title Clip

- apps/frontend/src/components/cards/controltable/ControlTable.vue
Closes #944, only shows Single Expand as on or off.
> Change v-switch Label to Only Show 'Single Expand'

- apps/frontend/src/components/cards/StatusChart.vue
- apps/frontend/src/components/cards/comparison/ChangeItem.vue
- apps/frontend/src/components/cards/comparison/CompareRow.vue
- apps/frontend/src/components/cards/comparison/DeltaView.vue
- apps/frontend/src/utilities/delta_util.ts
- apps/frontend/src/views/Compare.vue
- apps/frontend/tests/unit/Compare.spec.ts
Fixes overlay issues, improve searching, and remove a lot of unnecessary code.
Change behavior of "Display Only Changed Results" to show added and removed results as well.
Closes #941
> Cleanup code in Compare view

- apps/backend/src/evaluations/dto/evaluation.dto.ts
- apps/backend/src/evaluations/evaluations.controller.spec.ts
- apps/backend/src/evaluations/evaluations.controller.ts
- libs/interfaces/evaluation/evaluation.interface.ts
> Do not return data prop after evaluation create

- apps/frontend/src/components/global/sidebaritems/SidebarFileList.vue
- test/integration/database-results.spec.ts
Closes #1066, adds detection for profile files to SidebarFileList to fix uploading of profiles.
> Fix Uploading Profiles

- apps/frontend/src/components/global/upload_tabs/LoadFileList.vue
- apps/frontend/src/components/global/upload_tabs/SampleList.vue
Possibly closes #117, adds a loading bar while loading samples.
> Show Loading Bar when Loading Samples

- apps/frontend/src/components/global/upload_tabs/LoadFileList.vue
- apps/frontend/src/components/global/upload_tabs/SampleList.vue
Closes #1052, sets the default for sortBy on LoadFileList to createdAt and sorts descending by default.
> Sort Database by createdAt by Default

- .github/mergify.yml
Mergify is a tool that automatically makes sure the branch is up to date and then merges PRs. This means multiple PRs can be marked for merge and it will go down the list and merge each of them once checks pass and they are up-to-date with master.
> Add mergify configuration

- .github/workflows/push-to-npm.yml
- .gitignore
- README.md
- apps/frontend/package.json
- apps/frontend/src/server.js
- apps/frontend/vue.config.js
- package.json
- yarn.lock
Fixes #50, Fixes #232, Fixes #48, Fixes #51, Fixes #71, Fixes #103, Fixes #49, Fixes #100
> Fix scripts for building NPM package from heimdall-lite and automatically push to NPM on release

- apps/frontend/src/components/cards/controltable/ControlTable.vue
- apps/frontend/src/store/heights.ts
> Only Set ControlTable height in HeightsModule if it's defined

- apps/frontend/src/components/cards/treemap/Treemap.vue
- apps/frontend/src/components/global/ExportNist.vue
> Update language for nist exports and treemap to include privacy

- apps/frontend/src/components/cards/controltable/ControlRowHeader.vue
- apps/frontend/src/components/cards/controltable/ControlTable.vue
- apps/frontend/src/components/cards/controltable/ResponsiveRowLarge.vue
- apps/frontend/src/components/cards/controltable/ResponsiveRowMedium.vue
- apps/frontend/src/components/cards/controltable/ResponsiveRowSmall.vue
- apps/frontend/src/components/cards/controltable/ResponsiveRowSwitch.vue
Closes #1089, adds the filename to the leftmost column in ControlTable.
> Add "Results Set" column on left of ControlTable

- yarn.lock
Even with Dependabot, there are a few dependencies that have gotten out of date.
> Run a manual yarn upgrade

- test/package.json
- yarn.lock
Reverts mitre/heimdall2#1278
This is causing a lot of intermittent failures.
> Revert "Bump cypress from 6.8.0 to 7.2.0"

- apps/frontend/src/components/cards/controltable/ControlRowDetails.vue
Closes #1298, adds the CWE ID to the details tab.
> Add CWE ID to Details Tab

- apps/frontend/src/components/cards/EvaluationInfo.vue
- apps/frontend/src/utilities/delta_util.ts
Closes #1273, adds a run time to EvaluationInfo.
> Add Run Time to Results View

- apps/backend/config/app_config.ts
- apps/backend/src/config/config.service.ts
- apps/backend/src/main.ts
- yarn.lock
> Pass slightly different SSL options to Sequelize and postgresSessionStore

- yarn.lock
This fixes some of the open CVEs identified in our containers.
> Run a manual Yarn Upgrade to fix all updated missed by Dependabot

- apps/frontend/src/components/cards/ProfileInfo.vue
- yarn.lock
Closes #598, adds a profile inputs tab alongside the profile info tab.
> Add Profile Inputs Tab

- apps/backend/package.json
- apps/frontend/package.json
- apps/frontend/src/components/cards/ProfileInfo.vue
- apps/frontend/src/components/cards/SeverityChart.vue
- apps/frontend/src/components/cards/StatusCardRow.vue
- apps/frontend/src/components/cards/StatusChart.vue
- apps/frontend/src/components/generic/ApexPieChart.vue
- apps/frontend/src/store/data_filters.ts
- apps/frontend/src/store/search.ts
- apps/frontend/src/views/Results.vue
- lerna.json
- yarn.lock
Closes #1414, adds interactive filtering by clicking status count cards/charts and updates the search bar accordingly.
Depends on #1382
> Interactive Filtering

- apps/frontend/src/components/cards/EvaluationInfo.vue
- apps/frontend/src/store/evaluations.ts
- apps/frontend/src/views/Compare.vue
- apps/frontend/src/views/Results.vue
Closes #1415, adds the tag row to Compare.vue.
> Add TagRow to Compare View

- apps/frontend/src/components/global/RegistrationModal.vue
- apps/frontend/src/components/global/UserModal.vue
- apps/frontend/src/components/global/login/LocalLogin.vue
Closes #1465. Adds a spinner to the users' login and sign up button once clicked to indicate page loading.
> Animates Login and Sign up Buttons

- apps/frontend/package.json
- apps/frontend/src/components/cards/controltable/ControlRowHeader.vue
- apps/frontend/src/components/cards/treemap/Treemap.vue
- yarn.lock
Closes #77. Allow owners to change users group role.
> Use vuetify resize

- apps/frontend/package.json
- yarn.lock
> Revert "Bump sass from 1.32.13 to 1.35.1"

- apps/backend/src/interceptors/logging.interceptor.ts
Closes #1626, logs User-Agent and Referer headers.
> Log User Agent and Referer

- apps/frontend/src/components/cards/controltable/ControlRowHeader.vue
- apps/frontend/src/components/cards/controltable/ControlTable.vue
- apps/frontend/src/components/cards/controltable/ResponsiveRowLarge.vue
- apps/frontend/src/components/cards/controltable/ResponsiveRowMedium.vue
- apps/frontend/src/components/cards/controltable/ResponsiveRowSmall.vue
- apps/frontend/src/components/cards/controltable/ResponsiveRowSwitch.vue
- apps/frontend/src/components/generic/ColumnHeader.vue
Closes #1495. Add a way to mark controls as viewed.
> Added the ability to mark controls as viewed

- apps/backend/src/interceptors/logging.interceptor.ts
Place only timestamp within []
> Change logging.interceptor format

- apps/backend/src/database/database.module.ts
Closes #1646, logs SQL queries generated by Sequelize.
> Log Database Queries

- apps/backend/src/authn/authn.controller.ts
- apps/backend/src/config/config.service.ts
- apps/backend/src/main.ts
Closes #1665, uses secure cookies when in production mode.
> Use Secure Cookies in Production Mode

- apps/frontend/src/store/server.ts
- apps/frontend/src/views/Login.vue
Closes #1715, displays a Snackbar on logging out and clearing token.
> Add Log Off Snackbar

- test/package.json
- yarn.lock
> Revert "Bump cypress from 6.9.1 to 8.5.0"

- apps/backend/.env-example
- apps/backend/src/authn/authn.service.ts
Closes #2124, adds the ability to restrict users to one logged-in session.
> Allow One Session per User

- apps/frontend/src/components/global/ExportCSVModal.vue
> Fix Exporting Overlays as CSV

- apps/frontend/src/components/global/ExportCaat.vue
- apps/frontend/src/components/global/ExportHTMLModal.vue
- yarn.lock
Somehow dependabot misses some
> Run manual yarn upgrade

- apps/frontend/src/components/global/tags/TagRow.vue
Closes #2197, fixes evaluation tags combobox on the database page.
> Fix EvaluationTagRow

- apps/frontend/src/components/global/ExportCSVModal.vue
> Ensure Caveat is Displayed First in CSV Descriptions (if available)

- apps/frontend/src/views/Results.vue
Closes #2374, alphabetizes all Export options:
> Alphabetize Export Options

- apps/frontend/src/components/global/UserModal.vue
Closes #2435, shows the entire API key
> Show entire API key with overflow wrapped

- apps/frontend/src/components/global/HelpModal.vue
> Update Answer to "How to use Heimdall Lite 2.6.7"

- apps/backend/seeders/20200514154327-create-administrator.js
> Remove dependency on .env file existing

- libs/hdf-converters/src/mappings/AwsConfigMapping.ts
> revert change to awsconfigmapping to use lodash and do a clone of data

- .github/dependabot.yml
- apps/frontend/package.json
- yarn.lock
> Fix ExportCAAT

- apps/frontend/src/store/report_intake.ts
> Support Multi-file Return Filenames in Heimdall

- apps/frontend/src/components/global/ExportCSVModal.vue
> Export NIST Tags in CSV when CCIs are not Defined

- libs/hdf-converters/src/aws-config-mapper.ts
- libs/hdf-converters/src/fortify-mapper.ts
> Remove 'unmapped' NIST Tag from AWS Config Mapper and Fortify Mapper

- apps/frontend/src/components/cards/controltable/ControlRowDetails.vue
> Support JSON Syntax Highlighting on Code Tab

- libs/hdf-converters/sample_jsons/sonarqube_mapper/sonarqube-hdf.json
- libs/hdf-converters/src/sonarqube-mapper.ts
> Add project key to Sonarqube Mapper Output

- apps/frontend/src/components/cards/controltable/ControlRowHeader.vue
> Update NIST 800-53 Lookup URL

- apps/frontend/src/components/cards/controltable/ControlRowHeader.vue
> Set Filename Width for ControlRowHeader

- libs/hdf-converters/sample_jsons/sonarqube_mapper/sonarqube-hdf.json
- libs/hdf-converters/src/converters-from-hdf/asff/transformers.ts
- libs/hdf-converters/src/sonarqube-mapper.ts
> Prevent trailing slashes in HDF2ASFF and remove empty field in Sonarqube Mapper

- apps/frontend/src/components/global/ExportNist.vue
> Actually Increase i on Name Dedupe for 800-53 Export

- libs/hdf-converters/src/splunk-mapper.ts
Fixes an issue with using splunk2hdf on the SAF CLI
> Pass this.webCompatibility to checkSplunkCredentials

- apps/frontend/src/components/global/ExportHTMLModal.vue
> Account for Multiple Baselines in HTML Export

- libs/hdf-converters/test/mappers/reverse/xccdf_reverse_mapper.spec.ts
Fixes expecting hardcoded hdf-converters version number in test data.
> Fix HDF2XCCDF Spec

- libs/hdf-converters/README.md
Signed-off-by: Rlin232 <rlin@mitre.org>
> Updated hdf-converters README to list veracode as a supported format

- apps/frontend/src/store/report_intake.ts
- libs/hdf-converters/sample_jsons/twistlock_mapper/sample_input_report/twistlock-twistcli-coderepo-scan-sample.json
- libs/hdf-converters/sample_jsons/twistlock_mapper/twistlock-coderepo-hdf-withraw.json
- libs/hdf-converters/sample_jsons/twistlock_mapper/twistlock-coderepo-hdf.json
- libs/hdf-converters/src/twistlock-mapper.ts
- libs/hdf-converters/src/utils/fingerprinting.ts
- libs/hdf-converters/test/mappers/forward/twistlock_mapper.spec.ts
Signed-off-by: charleshu-8 <chu@mitre.org>
> Adding support for Twistlock code repo scans

- README.md
Updating the tables because they were out of date.
Updated `features` and `use cases` as well as some smaller edits.
Changing naming to Heimdall (Heimdall-Lite) and Heimdall with Backend (Server) --> This is up for discussion
Signed-off-by: Emily Rodriguez <ecrodriguez@mm279976-pc.lan>
> update tables and some language in the readme

- libs/hdf-converters/src/twistlock-mapper.ts
> handle case where 'vulnerabilities' attribute is null instead of an array

- apps/frontend/src/components/global/upload_tabs/FileReader.vue
updated list of convertable files to include everything that has a mapper and can be fingerprinted
resolves #3507 
> Update Converters List

- .gitignore
- setup-dev-env.sh
- setup-docker-env.sh
added more vim files to the .gitignore, made new lines show up properly in the setup scripts, made the 'y/n' behavior the same between the two scripts, made the password that the user was typing in hidden like password prompts ought to be tho it doesn't really matter too much cause we throw it in that .env file anyways
> Setup script fixes

- apps/frontend/src/views/Results.vue
Resolves https://github.com/mitre/heimdall2/issues/3020
> We should only export profile jsons in the profile view, i.e. no XCCDF/CAAT/CSV/HTML/whatever

- .github/workflows/push-server-to-docker.yml
- Dockerfile
1) Use ubi8 as the base instead of alpine
2) Ideally resolve the malformed dependencies issue by including the
tsconfigs as well as the package jsons before building
3) Specify a default value for NODE_ENV
4) Get rid of pointless permissions setting (esp in the builder)
5) Some stylistic improvements
> Update dockerfile to:

- apps/frontend/src/components/cards/ComplianceChart.vue
- apps/frontend/src/store/status_counts.ts
Resolves #4642
Instead of rounding, it does truncation at the end of the math process. Enforces a minimum resolution of four decimal points.
> No rounding in compliance chart

- apps/frontend/src/mixins/RouteMixin.ts
> checklistView fix search sync

- apps/frontend/src/components/global/ExportSplunkModal.vue
- apps/frontend/src/components/global/upload_tabs/splunk/SplunkReader.vue
> Update Splunk links

- libs/hdf-converters/package.json
- libs/hdf-converters/src/asff-mapper/asff-mapper.ts
- yarn.lock
> Using Semver Compare for ASFF "Previously HDF" Special Casing

- apps/frontend/src/components/global/Sidebar.vue
- apps/frontend/src/components/global/sidebaritems/DropdownContent.vue
- apps/frontend/src/components/global/sidebaritems/SidebarFileList.vue
- apps/frontend/src/store/data_filters.ts
- apps/frontend/src/store/evaluations.ts
- apps/frontend/src/store/report_intake.ts
- apps/frontend/src/store/search.ts
- apps/frontend/src/store/search_filter_sync.ts
- apps/frontend/src/views/Results.vue
First draft which has filename filtering working
Addresses #3857
> Filtering on groups and tags

- README.md
- apps/frontend/src/components/global/Snackbar.vue
- apps/frontend/src/components/global/admin/UserManagement.vue
- apps/frontend/src/components/global/login/LocalLogin.vue
- apps/frontend/src/store/snackbar.ts
- apps/frontend/src/views/Login.vue
- setup-dev-env.bat
- setup-dev-env.sh
**Files that use bcryptjs:**
**Require logic check**
Local Authentication Diagram
> Replace bcryptjs with WebCryptoAPI

- apps/backend/src/evaluations/evaluations.controller.ts
- apps/backend/src/evaluations/evaluations.service.ts
- apps/frontend/src/components/global/upload_tabs/DatabaseReader.vue
- apps/frontend/src/components/global/upload_tabs/SampleList.vue
> groupUsersBugFix

- apps/frontend/tailwind.config.js
- libs/hdf-converters/package.json
- yarn.lock
> Revert "Bump tw-elements from 1.1.0 to 2.0.0"
